"""Base migration!

Revision ID: 19111d0fb558
Revises: 
Create Date: 2017-06-10 19:53:43.944928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19111d0fb558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('braintree_master_merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_braintree_master_merchant_public_id'), 'braintree_master_merchant', ['public_id'], unique=True)
    op.create_table('contact_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_contact_submissions_public_id'), 'contact_submissions', ['public_id'], unique=True)
    op.create_table('email_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email_to', sa.String(length=64), nullable=False),
    sa.Column('email_from', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_public_id'), 'email_queue', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('local_tz', sa.String(length=32), nullable=False),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=False),
    sa.Column('five_min_price', sa.DECIMAL(), nullable=True),
    sa.Column('fifteen_min_price', sa.DECIMAL(), nullable=True),
    sa.Column('thirty_min_price', sa.DECIMAL(), nullable=True),
    sa.Column('sixty_min_price', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('extended_address', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('country_code_alpha2', sa.String(length=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_country_code', 'addresses', ['country_code_alpha2'], unique=False)
    op.create_index('idx_default_addresses', 'addresses', ['is_default'], unique=False)
    op.create_index('idx_locality', 'addresses', ['locality'], unique=False)
    op.create_index('idx_postal_code', 'addresses', ['postal_code'], unique=False)
    op.create_index('idx_region', 'addresses', ['region'], unique=False)
    op.create_index(op.f('ix_addresses_public_id'), 'addresses', ['public_id'], unique=True)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('braintree_sub_merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('master_merchant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('braintree_account_id', sa.String(length=24), nullable=False),
    sa.Column('service_fee_percent', sa.DECIMAL(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('address_street_address', sa.String(length=128), nullable=False),
    sa.Column('address_locality', sa.String(length=32), nullable=False),
    sa.Column('address_region', sa.String(length=32), nullable=False),
    sa.Column('address_zip', sa.String(length=12), nullable=False),
    sa.Column('register_as_business', sa.Boolean(), nullable=False),
    sa.Column('legal_name', sa.String(length=64), nullable=True),
    sa.Column('dba_name', sa.String(length=64), nullable=True),
    sa.Column('bus_address_street_address', sa.String(length=128), nullable=True),
    sa.Column('bus_address_locality', sa.String(length=32), nullable=True),
    sa.Column('bus_address_region', sa.String(length=32), nullable=True),
    sa.Column('bus_address_zip', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['master_merchant_id'], ['braintree_master_merchant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_braintree_sub_merchant_public_id'), 'braintree_sub_merchant', ['public_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('scheduling_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_user_id', sa.String(length=36), nullable=False),
    sa.Column('utc_start', sa.DateTime(), nullable=False),
    sa.Column('utc_end', sa.DateTime(), nullable=False),
    sa.Column('day_number', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_tz_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_tz_end', sa.DateTime(), nullable=False),
    sa.Column('scheduling_tz_start', sa.DateTime(), nullable=False),
    sa.Column('scheduling_tz_end', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(), nullable=False),
    sa.Column('service_fee', sa.DECIMAL(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_user_id'], ['users.public_id'], ),
    sa.ForeignKeyConstraint(['scheduling_user_id'], ['users.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_events_public_id'), 'events', ['public_id'], unique=True)
    op.create_index(op.f('ix_events_scheduled_user_id'), 'events', ['scheduled_user_id'], unique=False)
    op.create_index(op.f('ix_events_scheduling_user_id'), 'events', ['scheduling_user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('utc_open', sa.DateTime(), nullable=False),
    sa.Column('utc_end', sa.DateTime(), nullable=False),
    sa.Column('day_number', sa.SmallInteger(), nullable=False),
    sa.Column('local_tz', sa.String(), nullable=False),
    sa.Column('local_tz_open', sa.DateTime(), nullable=False),
    sa.Column('local_tz_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_schedules_public_id'), 'schedules', ['public_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('submerchant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('service_fee', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submerchant_id'], ['braintree_sub_merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_payments_public_id'), 'payments', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_public_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_schedules_public_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_events_scheduling_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_scheduled_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_public_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_braintree_sub_merchant_public_id'), table_name='braintree_sub_merchant')
    op.drop_table('braintree_sub_merchant')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_public_id'), table_name='addresses')
    op.drop_index('idx_region', table_name='addresses')
    op.drop_index('idx_postal_code', table_name='addresses')
    op.drop_index('idx_locality', table_name='addresses')
    op.drop_index('idx_default_addresses', table_name='addresses')
    op.drop_index('idx_country_code', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_email_queue_public_id'), table_name='email_queue')
    op.drop_table('email_queue')
    op.drop_index(op.f('ix_contact_submissions_public_id'), table_name='contact_submissions')
    op.drop_table('contact_submissions')
    op.drop_index(op.f('ix_braintree_master_merchant_public_id'), table_name='braintree_master_merchant')
    op.drop_table('braintree_master_merchant')
    # ### end Alembic commands ###
