"""Added necessary columns for account verification.

Revision ID: 28db7bc84a9d
Revises: 4cbbf9b64d5d
Create Date: 2017-06-12 21:14:39.880773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28db7bc84a9d'
down_revision = '4cbbf9b64d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_queue', ['id'])
    op.add_column('users', sa.Column('is_validated', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('verify_token', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_verify_token'), 'users', ['verify_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verify_token'), table_name='users')
    op.drop_column('users', 'verify_token')
    op.drop_column('users', 'is_validated')
    op.drop_constraint(None, 'email_queue', type_='unique')
    # ### end Alembic commands ###
