"""Adding braintree customer table for subscriptions.

Revision ID: 43756838ec79
Revises: edd66f0ffbc4
Create Date: 2017-09-05 22:02:39.146558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43756838ec79'
down_revision = 'edd66f0ffbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('braintree_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('braintree_customer_id', sa.String(), nullable=False),
    sa.Column('credit_card_token', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('braintree_customer_id'),
    sa.UniqueConstraint('credit_card_token'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_braintree_customer_public_id'), 'braintree_customer', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_braintree_customer_public_id'), table_name='braintree_customer')
    op.drop_table('braintree_customer')
    # ### end Alembic commands ###
