"""Adding email queue and triggers.

Revision ID: 4cbbf9b64d5d
Revises: d25b343c8037
Create Date: 2017-05-29 17:48:57.874077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbbf9b64d5d'
down_revision = '19111d0fb558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION notify_mail_insert()
        RETURNS trigger AS $$
        DECLARE
          current_row RECORD;
        BEGIN
          IF (TG_OP = 'INSERT') THEN
            current_row := NEW;
          ELSE
            current_row := OLD;
          END IF;
        PERFORM pg_notify(
            'new_mail',
            json_build_object(
              'table', TG_TABLE_NAME,
              'type', TG_OP,
              'id', current_row.id,
              'data', row_to_json(current_row)
            )::text
          );
        RETURN current_row;
        END;
        $$ LANGUAGE plpgsql;

        create trigger notify_mail_insert_trg after insert on email_queue for each row execute procedure notify_mail_insert();
        """
    )
    op.create_unique_constraint('uqc_address_id', 'addresses', ['id'])
    op.create_unique_constraint('uqc_bt_master_merch_id', 'braintree_master_merchant', ['id'])
    op.create_unique_constraint('uqc_bt_submerchant_id', 'braintree_sub_merchant', ['id'])
    op.create_unique_constraint('uqc_contact_submissions_id', 'contact_submissions', ['id'])
    op.create_unique_constraint('uqc_events_id', 'events', ['id'])
    op.create_unique_constraint('uqc_payments_id', 'payments', ['id'])
    op.create_unique_constraint('uqc_schedules_id', 'schedules', ['id'])
    op.create_unique_constraint('uqc_users_id', 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'schedules', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_constraint(None, 'contact_submissions', type_='unique')
    op.drop_constraint(None, 'braintree_sub_merchant', type_='unique')
    op.drop_constraint(None, 'braintree_master_merchant', type_='unique')
    op.drop_constraint(None, 'addresses', type_='unique')
    op.drop_index(op.f('ix_email_queue_public_id'), table_name='email_queue')
    # ### end Alembic commands ###
