"""Adding total price to payment table.

Revision ID: cbfae2e15803
Revises: 28db7bc84a9d
Create Date: 2017-06-13 20:33:21.549550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfae2e15803'
down_revision = '28db7bc84a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('base_amount', sa.DECIMAL(), nullable=False))
    op.add_column('payments', sa.Column('total_price', sa.DECIMAL(), nullable=False))
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'total_price')
    op.drop_column('payments', 'base_amount')
    # ### end Alembic commands ###
