"""Adding the concept of a username to users.

Revision ID: edd66f0ffbc4
Revises: 62a91ccf40e0
Create Date: 2017-08-06 17:27:39.522724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd66f0ffbc4'
down_revision = '62a91ccf40e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=32), nullable=False))
    op.create_unique_constraint('unique_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_users_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
